# do not touch this line
configVersion: 2

description: connects to server
keywords: ''
name: client
displayName: Client

events:
  - reset
  - listtags

services:
  re:
    engine: recognition
    type: face 

